### ISSUE TITLE
Animation Effect

### ISSUE THREAD

**Issue by mxklb** [codeSessionsP2/masimapage#7]
Add css video effects to the logo and the green 'play' button.

**Comment by smnwndrr** [comment]
Did a rough sketch on my smnwdrr/masimapage branch animation. I don't know how to show it without merging it into my gh-pages branch.

**Comment by mxklb** [comment]
there's no other option to show it to me using gh-pages than merging it into, besides letting me clone your repo and simply checkout your branch animation ;) I'll do so if I find time to .. 

P.S. Review although the other issues where I'll describe linking commits to gh issues.

**Comment by smnwndrr** [comment]
two ideas: 
1. animation only on css level, caveat only css transforms possible
2. apply svg filters, toggle them via js. [here](http://www.smashingmagazine.com/2015/05/why-the-svg-filter-is-awesome/) is an interesting article about svg filters, caveat: does not work on windows software.

**Comment by mxklb** [comment]
I reviewed your css skew animation, this looks promising .. I think both solutions are possible. We could work it out by time. Nevertheless providing a first nice animation would be nice if we launch the page. So css transform is what I think we're more confirm with, so let's first of all stick to this .. 

Some Responsive Ideas:
- During active audio playing the hover effect (rotating the logo/player) could be animated infinitely
- During pause or stop the logo is animated if not in hover mode. In hover player is shown. 

Animation Ideas:
- The background of the logo (player) could blink/flicker randomly through the logo
- The already mentioned old video flickering style animation of the logo 
- Or whatever comes to your mind

**Comment by mxklb** [comment]
@smnwndrr if you find time, review [mxklb.github.io/masimapage](http://mxklb.github.io/masimapage/) 

I added tv noise flickering and logo wobbling. I think maybe needs some more slight adjustments but overall this looks somehow like I thought it should look :)
