### ISSUE TITLE
@facefont embbed Fonts

### ISSUE THREAD

**Issue by mxklb** [codeSessionsP2/masimapage#9]
All used fonts should be available locally

**Comment by smnwndrr** [comment]
Hi, have a look at: http://stackoverflow.com/questions/8966740/how-to-host-google-web-fonts-on-my-own-server. If your time is scarce, assign this issue to me.

**Comment by mxklb** [comment]
Please review how it is done on my xamblak.de landing page. I think what I did there is a little more straight forward (copy font sources to page and simply link to it there) but I don't know if it was done right or if it has any flaw backs .. if so let me know, otherwise I would have done it as on xamblak.de ..?

**Comment by smnwndrr** [comment]
I can't see how your xamblak.de page is different to the link posted above. The link just states known caveats with this method. So just do it!

**Comment by mxklb** [comment]
If fonts are finally chosen and I find time I'll do so ..

**Comment by mxklb** [comment]
Please review my fontface branch/commit. If you can confirm this is finished and may be merged into p2coders .. what do you think, all done here, should I do a PR to the official masima.rocks?

Note: Merging a PR into p2coders still lacks the #11 merge ignore issue due to the early CNAME deleting commit (65fa535) in our development forks! 

So this would be a good situation to work or test a solution for #11.

**Comment by mxklb** [comment]
My latest gh-pages contains all changes.

**Comment by mxklb** [comment]
p.s. merge into production is still missing (release launch date tbd)
